Capstone
Mehria-Rahmani/capstone-1 pull request #1
Opened 2022-06-29 12:21 UTC by Mehria-Rahmani

The content of  page are personalized. Choose a topic that is different.

design that i followed:  [design guidelines](https://www.behance.net/gallery/29845175/CC-Global-Summit-2015), including:

Colors.
Typography: font face, size and weight.
Layout: composition and space between elements.
The pages look almost identical to the original design. Small adjustments like text or image changes are acceptable.

build  these 2 pages:
The home page.
The about page.
Each of these pages  have versions for 2 different screen sizes:

Mobile: up to 768px wide.
Desktop: 768px or wider.

2022-06-29 13:19 UTC, ShoiraTa requested changes
Hi @Mehria-Rahmani ,

:thumbsup: This is good to make it this far, your project is really nice, congratulations on the good work you have done so far.

**First let me to point out:**

- Great commit history! ✔️ 
- You passed all the Linters! ✔️ 
- Professional pull request! ✔️ 

Keep on coding, good job so far! :clap:

There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media.giphy.com/media/dEPGknRiEniec/giphy.gif" width="500" height="250" />

 ## Required Changes  :recycle: 

_Check the comments under the review._ 

***
Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear by mentioning my Github username.


**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

* * *
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-29 13:19 UTC, ShoiraTa commented on README.md
- [ ] Kindly add credits to [Cindy Shin](https://www.behance.net/adagio07) the [author of the original design](https://www.behance.net/gallery/29845175/CC-Global-Summit-2015), as required by the [Creative Commons License](https://creativecommons.org/licenses/).

2022-06-29 13:19 UTC, ShoiraTa commented on about.html
> +      <hr class="horizontal-line text-center" />
- [ ] in Desktop Size, About Page's footer should have a dark background

Your design  | Provided design
------------- | -------------
<img width="774" alt="Screenshot 2022-06-29 at 17 15 27" src="https://user-images.githubusercontent.com/77038610/176445338-d37a5bfb-a56b-4fe9-8ee7-7bcac3d793ac.png">  | <img width="845" alt="Screenshot 2022-06-29 at 17 14 57" src="https://user-images.githubusercontent.com/77038610/176445231-e20622d1-247a-417c-be23-3960336fcbda.png">
.

2022-06-29 13:19 UTC, ShoiraTa commented on about.html
> +        <div class="past-second-activity act">
- [ ] the background image in the first card is missing, kindly add a background image 👍🏻 
<img width="755" alt="Screenshot 2022-06-29 at 17 17 09" src="https://user-images.githubusercontent.com/77038610/176445663-65fadedf-9255-4399-b065-88c68ec48585.png">

2022-06-29 15:13 UTC, Mihndim2020 requested changes
## Hi @Mehria-Rahmani, 

Great work on making the changes requested by a previous reviewer 👏 👏 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.
![stay-strong-youre-almost-there](https://user-images.githubusercontent.com/65852621/133678845-1b015b27-e9bc-4784-a316-bc699db8237a.jpg)


 # Status: Requires Changes ♻️
_Check the comments under the review._

# Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-29 17:59 UTC, Gambit142 requested changes
Hi @Mehria-Rahmani 👋, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
- Added background-image to cards on about page ✔️ 
- Gave credits to Cindy Shin the designer of the template used ✔️ 


 ## Required Changes ♻️
_Kindly Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-29 17:59 UTC, Gambit142 commented on about.html
> +      <hr class="horizontal-line text-center" />
- [ ] Great work making the changes requested by the previous reviewers. To make your project complete, kindly implement the final change requested by the previous reviewers by making the `background-color` of the `footer` tag with class `.footer` on the about page `#272a31`. After doing this, you can adjust the `color` of the fonts to be a bright `color` for accessibility purposes. Implementing this change will ensure that your project is identical to that of the template provided by Cindy Shin. Kindly implement this change 👍

2022-06-30 04:48 UTC, ShoiraTa approved these changes
## **STATUS: APPROVED  🟢 ** 
------
### Hi @Mehria-Rahmani , 

**Great work on making the changes requested by a previous reviewer 👏🏻** 

Your project is complete! . There is nothing else to say other than... it's time to merge it 🍾🚢 :shipit: . Congratulations!  🎉💯🌟 

![5SW](https://user-images.githubusercontent.com/77038610/154919611-7d0675af-6364-45a3-92d6-eccd9b743ced.gif)

**Cheers and Happy coding! :clap: :clap: :clap:**

Feel free to leave any questions or comments in the PR thread by mentioning my Github username if something is not 100% clear.
***
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have  limited number of  reviews per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-30 04:48 UTC, ShoiraTa commented on index.html
> +      <button
- [ ] OPTIONAL: The featured speakers section was aligned in two columns when I first reviewed, now it looks like the changes you made affected this section and it became a single column. I strongly recommend to bring back the previous implementation 👍🏻 

Your design  | Behance design
------------- | -------------
<img width="710" alt="Screenshot 2022-06-30 at 08 45 21" src="https://user-images.githubusercontent.com/77038610/176594703-e53d4ec8-7c9d-4e97-9c17-d03d04804ee1.png"> | <img width="866" alt="Screenshot 2022-06-30 at 08 47 03" src="https://user-images.githubusercontent.com/77038610/176594862-3400eb37-e099-4d41-a7c4-3177ed60d2c8.png">

2022-06-30 04:50 UTC, Mehria-Rahmani commented
Thank u so much

On Thu, Jun 30, 2022, 9:18 AM Shoira ***@***.***> wrote:

> ***@***.**** approved this pull request.
> **STATUS: APPROVED 🟢 **
> ------------------------------
> Hi @Mehria-Rahmani <https://github.com/Mehria-Rahmani> ,
>
> *Great work on making the changes requested by a previous reviewer 👏🏻*
>
> Your project is complete! . There is nothing else to say other than...
> it's time to merge it 🍾🚢 [image: :shipit:] . Congratulations! 🎉💯🌟
>
> [image: 5SW]
> <https://user-images.githubusercontent.com/77038610/154919611-7d0675af-6364-45a3-92d6-eccd9b743ced.gif>
>
> *Cheers and Happy coding! 👏 👏 👏*
>
> Feel free to leave any questions or comments in the PR thread by
> mentioning my Github username if something is not 100% clear.
> ------------------------------
>
> *As described in the Code reviews limits policy
> <https://microverse.zendesk.com/hc/en-us/articles/1500004088561> you have
> limited number of reviews per this project. If you think that the code
> review was not fair, you can request a second opinion using this form
> <https://airtable.com/shrQAqnBwek5a0O0s>.*
> ------------------------------
>
> In index.html
> <https://github.com/Mehria-Rahmani/capstone-1/pull/1#discussion_r910601884>
> :
>
> > +        Featured Speakers
>
> +      </h2>
>
> +      <hr class="horizontal-line text-center" />
>
> +      <div class="speakers-list"></div>
>
> +      <button
>
>
>
>    - OPTIONAL: The featured speakers section was aligned in two columns
>    when I first reviewed, now it looks like the changes you made affected this
>    section and it became a single column. I strongly recommend to bring back
>    the previous implementation 👍🏻
>
> Your design Behance design
> [image: Screenshot 2022-06-30 at 08 45 21]
> <https://user-images.githubusercontent.com/77038610/176594703-e53d4ec8-7c9d-4e97-9c17-d03d04804ee1.png> [image:
> Screenshot 2022-06-30 at 08 47 03]
> <https://user-images.githubusercontent.com/77038610/176594862-3400eb37-e099-4d41-a7c4-3177ed60d2c8.png>
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Mehria-Rahmani/capstone-1/pull/1#pullrequestreview-1024258063>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AYG63GEAPBHMXE4NZ32UI43VRURJHANCNFSM52FRK6ZA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-06-30 04:57 UTC, merged

2023-01-30 07:25 UTC, milen-ale commented on index.html
> +      <button
-[ ] Great work making the changes requested by the previous reviewers. To make your project complete, kindly implement the final change requested by the previous reviewers The featured speakers section was aligned in two columns when I first reviewed it, now it looks like the changes you made affected this section and it became a single column. I strongly recommend to bring back the previous implementation 👍🏻